name: Web App to ECR

on:
  push:
    branches: [dev]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        run: |
          docker build -t web-app .
          docker tag web-app:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:latest

  # Deploy on EC2
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Write SSH key to file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts || true

      - name: Test SSH connection to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} hostname

      - name: Deploy Web App to EC2 with SSL
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -ex
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

            docker stop webapp || true
            docker rm webapp || true

            docker pull $ECR_REPOSITORY:latest

            docker run -d \
              -e FINERACT_API_URL=https://web-app-santi-fiter-test.duckdns.org \
              -e FINERACT_API_URLS=https://web-app-santi-fiter-test.duckdns.org \
              -e FINERACT_PLATFORM_TENANT_IDENTIFIER=default \
              --name webapp \
              -p 4200:4200 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              $ECR_REPOSITORY:latest

            docker logs --tail 50 webapp
          EOF
